### ISSUE TITLE
Broken bot since threads update

### ISSUE THREAD

**Issue by Carhenia** [xzefir/CordCraft-sponge#1]
New threads update seems to have broken the bot, mc -> discord communication does not work but discord -> mc does, it just seems to be very delayed. 

?connection command confirms that the bot is set up correctly. It was working fine up until 5 hours ago,

**Comment by xzefir** [comment]
The problem is normally resolved! Tomorrow I will update the bot to fix this bug permanently. Thanks for report.

**Comment by Carhenia** [comment]
Thank you! seems to be working again :)
