### ISSUE TITLE
Bot needs verification.

### ISSUE THREAD

**Issue by hanonsilverleaf** [xzefir/CordCraft-sponge#2]
As the bot has been used by over a 100 servers, discord limits the bot from joining any further servers until the owner of the bot gets it verified.
We are unable to use the bot unless xzefir verifies it.

**Comment by xzefir** [comment]
True ! I will do it quickly.

**Comment by xzefir** [comment]
This is good ! The bot is certified, you can invite the bot on your Discord server !
